### ISSUE TITLE
Not loading alarm list

### ISSUE THREAD

**Issue by DavidCroenne** [Tertiush/Alarmin-Android-App#53] opened 2019-02-06 10:35 UTC
As stated by other users on playstore reviews, after upgrade to Android firmware 9.0, Alarmin freezes on homepage "1. loading alarms..." , Reinstalation didnt help. On another older mobilephone it work ok. 

Here are the logs in verbose:
```***Logs:*** 

App version: 1.4.1 ,build: 104018

Opening alarm: loading alarms.... | undefined | undefined 
home Ctrl - Got compressedView: false | undefined | 24 
Opening alarm with compressed view set at: false | undefined | 2 
Viewing logs | undefined | 3971 
Please add some detail about your issue in this email (at the top)```

**Comment by Tertiush** [comment] 2019-02-06 13:41
Hi - thanks for posting this.

To be honest I haven't touched the codebase for probably a year now, mainly as its stable and I've decided to spend time elsewhere. Fact is the project started as a hobby and turned into an app lol.

In any case, I will make a plan to compile the code against the latest Android SDK and see what I can learn from that. Hopefully I can get this done over the weekend. If I do get any success I'll post an APK here for testing.

**Comment by DavidCroenne** [comment] 2019-02-06 13:56
Hi (I shall have started with that, indeed :flushed:) Tertiush, thanks for your quick reply!
Let me know if I can help doing tests on my 9.0 platform.

**Comment by Tertiush** [comment] 2019-02-07 09:15
Last night I updated my Android SDK tools and spinned up a Android Pie virtual machine. Sadly the app still works so its definitely not the vanilla Pie that breaks it. Two options going forward: Update any other relevant tools such as the web viewer and see if it fails, and/or rework the database backend to not use indexedDb (which I suspect is causing the failure). I'll give the former a try first and if its going nowhere then the latter. In short please bear with me I'm working on it.
![image](https://user-images.githubusercontent.com/11636364/52401070-86362800-2ac9-11e9-93c2-849fc2f2c24f.png)

**Comment by Tertiush** [comment] 2019-02-07 12:41
I was able to reproduce the issue, although the root cause is still unknown. Nevertheless please try this apk:
https://github.com/Tertiush/Alarmin-Android-App/blob/master/Development/android-release.apk

**Comment by DavidCroenne** [comment] 2019-02-07 13:46
It's better, the correct alarm is loading in the list.
But when i select the alarm, nothing appears:

**Comment by Tertiush** [comment] 2019-02-08 19:14
I may have managed to fix the loading of the alarms (when tapping on them), although I can only confirm this in an Android emulator as my phone is a tad outdated. There is a risk that you might loose your settings (I did with my outdated phone) - push notifications should however still work as this is as dependent on the app's stability.

I am still investigating why my settings were lost, but if anyone else experiences the same please let me know. Many thanks for helping out here!! Use the same link in my previous post to download the update: https://github.com/Tertiush/Alarmin-Android-App/blob/master/Development/android-release.apk

**Comment by DavidCroenne** [comment] 2019-02-09 10:33
Thanks again for keeping working on this.
I could try the app, did not lose any settings. 
The alarm is now connected, but the alarm page do not open, the app stay on the alarm list page. 
See screenshot and logs.

```
***Logs:*** 

App version: 1.5.2 ,build: 105028

Alarm list successfully retrieved | undefined | undefined 
Opening alarm: 6Fredeau | undefined | 2688 
home Ctrl - Got compressedView: false | undefined | 29 
Opening alarm with compressed view set at: false | undefined | 2 
Checking IP... | undefined | 3 
Checking IP now: https://192.168.0.17:443 | undefined | 1 
Checking IP... | undefined | 1 
Good HTTP response for IP, resolving | undefined | 1048 

```

**Comment by alvarolobato** [comment] 2019-02-09 11:08
I have the exact same situation.

**Comment by Tertiush** [comment] 2019-02-14 06:34
I am not seeing the behavior as above on my emulator or my phone. My alarm connects and remain in the alarm. At what point does the alarm disappear to the alarm list view? Can you clear the cache and configure the alarm again to see if it still does that? thanks

**Comment by d4zza** [comment] 2019-02-14 08:20
I've loaded the updated version and also experiencing the same @DavidCroenne. The event's log populates correctly I see.

**Comment by Tertiush** [comment] 2019-02-14 10:41
Hi, I need to know the exact sequence of events to the point where the app gets stuck. I cannot help anyone before I know this as my app functions correctly. A video will actually work best.

**Comment by DavidCroenne** [comment] 2019-02-14 22:00
Hi, here is a [screencast](https://drive.google.com/file/d/1Vh8BTdKsfTFqkAO8GtVtv19JG0Sku7L5/view?usp=sharing)
I connect to the alarm, check the menu, disconnect, then connect again.
Hope this helps, thanks again for your efforts!

**Comment by Tertiush** [comment] 2019-02-15 05:32
Thanks @DavidCroenne 

Am I right in saying you have the "automatic connect" to the alarm option activated? I activated mine and got the same issue at first. Try disabling it and see if that helps. In the meantime I will look at the relevant code for the auto connect portion.

**Comment by DavidCroenne** [comment] 2019-02-15 09:07
Good point, I should have thought about it by myself.
I've disabled auto connection, does not look better, see new [screencast](https://drive.google.com/file/d/1OULndyqSJYkTAX0mqPfff4VSnYIvfyIC/view?usp=sharing), where I try to connect twice to the alarm, then open the settings.

**Comment by Tertiush** [comment] 2019-02-15 16:45
@DavidCroenne One more favor please... 

Make sure in your settings logs are set to verbose. Then open the alarm again, connect and tap the alarm a few times. Then disconnect and send me the log directly from the app (don't post it here). I'm trying to figure out where in the app's logic it is hanging. thanks!

**Comment by DavidCroenne** [comment] 2019-02-15 17:36
Done.

**Comment by Tertiush** [comment] 2019-02-18 14:08
Hi all

I am having immense issues with resolving this bug as the framework I used (Ionic 1) is very outdated and support limited. Mobile/web develop not being my day-job but a mere interest makes me believe someone else can do a much better job at creating and maintaining a solution we could all hopefully benefit from. 

That being said, I am willing to share most of the code for this project if someone willing, or alternatively open-source it here on GitHub. I will not share any sensitive data pertaining to the current users, e.g. the backend db managing push notifications. I will however share the relevant code snippets to get another backend/push solution going. It would be nice if a open-source solution can be driven and maintained here on GH, that will be first prize but would require a re-thing of the code base.

If there's any takers please get in touch with me.

**Comment by Tertiush** [comment] 2019-02-18 14:20
I've opened a separate issue to discuss my previous comment: https://github.com/Tertiush/Alarmin-Android-App/issues/54

**Comment by DavidCroenne** [comment] 2019-03-14 10:03
Hi Tertius, looks like there are not so many candidates :(
I'm not developer, but if ever I can help installing some developer kit and do advanced testing on my Android Pie, I'd be happy to help.

**Comment by Tertiush** [comment] 2019-03-14 11:16
Haha indeed, not a single person. I took delivery of my Pixel 3 yesterday and for some reason the app works perfectly fine for me (also on Pie). This makes me wonder if Google might have released some bugfix/patch that fixed this issue. I have Chrome version 72.0.3626.121 installed. What version is your Chrome?

**Comment by DavidCroenne** [comment] 2019-03-14 11:29
Hey, great, happy for you, and hope is back! 
Just checked, I have exactly the same Chrome version. However, my default app to open webpages is Opera Mini. I still have the same hang on "(IP)read...(WAN)" in the app after connecting to the alarm.
Android version 9 - security patch Feb, 5th
Alarmin build 105028

**Comment by Tertiush** [comment] 2019-03-15 17:44
Update: An user has emailed me to say that after a recent android update their app started working again. He is on Android 9 (Pie). He updated his Samsung S8 to the latest patch release. I still think it has something to do with Chrome, as it is used as Android's Webview applet as of Android 4.4. Let's hope everyone gets this update soon, via a Chrome update.

**Comment by DavidCroenne** [comment] 2019-03-18 13:28
And.... It finally also works for me!!
I have not updated Chrome the last days, no idea what changed on my configuration ..
I'm deeply sorry for all the efforts this caused you :(

**Closed** 2019-03-18 13:29 UTC
